name: 'Algolia Crawler Automatic Crawl'
description: 'Automatically trigger a crawl and push to Algolia, when deploying a website using the Algolia Crawler.'
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  # CREDENTIALS
  crawler-user-id:
    description: 'Crawler user ID'
    required: true
  crawler-api-key:
    description: 'Crawler API key'
    required: true
  crawler-api-base-url:
    description: 'Crawler API URL'
    required: false
    default: 'https://crawler.algolia.com/api/1'
  github-token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}

  # CRAWLER CONFIGURATION
  crawler-name:
    description: 'Name of the crawler'
    required: true
    default: '[Github] ${{ github.repository }} ${{ github.ref }}'
  algolia-app-id:
    description: 'Algolia Application ID'
    required: true
  algolia-api-key:
    description: 'Algolia API key'
    required: true
  site-url:
    description: 'url of the site to crawl'
    required: true
  override-config:
    description: 'Override config in case the crawler is already existing'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'build/index.js'
