---
aliases:
  # Forward the current folder when using wokflows
  #   persist-to-workspace & attach-workspace
  - &persist-work-dir
    root: .
    paths: .

  - &attach-work-dir
    at: ~/project/

  # Dependencies
  - &yarn
    name: Run Yarn
    command: |
      yarn install --non-interactive --cache-folder ~/.cache/yarn
defaults: &defaults
  working_directory: ~/project

version: 2

jobs:
  checkout:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run: *yarn
      - persist-to-workspace: *persist-work-dir

  lint:
    <<: *defaults
    docker:
      - image: cimg/node:14.18.1

    steps:
      - attach-workspace: *attach-work-dir
      - run: yarn lint

  test:
    <<: *defaults
    docker:
      - image: cimg/node:14.18.1

    steps:
      - attach-workspace: *attach-work-dir
      - run: yarn test

  release:
    <<: *defaults
    docker:
      - image: cimg/node:14.18.1
    steps:
      - attach-workspace: *attach-work-dir
      - run: yarn build && yarn compile && yarn semantic-release

workflows:
  version: 2
  suite:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - release:
          requires:
            - test
            - lint
          filters:
            branches:
              only: main
