name: Github Pages -> Algolia Crawler
on:
  push:
    branches: [ main ]

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sleep for 30s
        run: sleep 30
      - name: Github-pages-MAIN => Algolia crawler creation and recrawl (Push on Main branch)
        uses: ./
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1'
          crawler-name: gpages-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://community.algolia.com/algoliasearch-crawler-github-actions/public/github-pages/'
          override-config: true
