name: Vercel automatic reindexing with Algolia Crawler
on:
  issue_comment:
    types: [edited]

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: algolia/algoliasearch-crawler-github-actions 
          ref: v0.4.2
      - name: Sleep for 30s
        run: sleep 30
      - name: Capture Vercel preview URL
        if: github.event.comment.author == 'vercel'
        id: vercel_preview_url
        uses: aaimio/vercel-preview-url-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      - name: Vercel-PR => Algolia crawler creation and reindex on preview (Pull Request)
        if: github.event.comment.author == 'vercel'
        uses: ./
        id: crawler_pr
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1/'
          crawler-name: vercel-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
