name: Vercel automatic reindexing with Algolia Crawler
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # set default env for pushes on main
      - run: export ENV_TO_CRAWL=algoliasearch-crawler-github-actions.vercel.app
      - run:  echo "::set-env name=ENV_TO_CRAWL::$ENV_TO_CRAWL"
      # Action to retrieve the Preview URL in case it's a pull request
      - name: Get deployment URL
        if: github.ref != 'refs/heads/main'
        id: deployment-get-url
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 1 
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
      # Replace default url with preview
      - id: set-preview-url
        if: github.ref != 'refs/heads/main'
        run: export ENV_TO_CRAWL=${{ steps.deployment.outputs.deployment }}
        run: echo "::set-env name=ENV_TO_CRAWL::$ENV_TO_CRAWL"
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: algolia/algoliasearch-crawler-github-actions 
          ref: v0.4.2
      - name: Vercel-PR => Algolia crawler creation and reindex on preview (Pull Request)
        uses: ./
        id: crawler_pr
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1/'
          crawler-name: vercel-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: $ENV_TO_CRAWL
